services:
  nginx:
    build: 
      context: ../autodeclic-react
      dockerfile: Dockerfile.preprod
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.preprod.conf:/etc/nginx/conf.d/default.conf:ro
      - /opt/certbot/www:/var/www/certbot:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      symfony:
        condition: service_healthy
      # python:
      #   condition: service_started
    networks:
      - autodeclic-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 10s
      timeout: 5s
      retries: 3
    
  
  symfony:
    build: 
      context: ../autodeclic-symfony
      dockerfile: Dockerfile.preprod
    container_name: symfony
    networks:
      - autodeclic-network
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "php", "bin/console", "doctrine:query:sql", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - ../autodeclic-symfony:/app
      - ~/.config/gcloud:/root/.config/gcloud

  database:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - autodeclic-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # python:
  #   build:
  #     context: ../autodeclic-python
  #     dockerfile: Dockerfile.preprod
  #   container_name: python
  #   command: uvicorn app.main:app --host 0.0.0.0 --port 8000
  #   environment:
  #     - OPENAI_API_KEY=${OPENAI_API_KEY}
  #   volumes:
  #     - ../autodeclic-python:/app
  #   networks:
  #     - ${DOCKER_NETWORK}
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
  #     start_period: 10s
      
volumes:
  chrome_data:
  mysql_data:
  
networks:
  autodeclic-network:
    external: true